name: run main.py

on:
  schedule:
    # - cron: '15 0 * * *' # At 00:15 UTC every day
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
         uses: actions/setup-python@v4
         with:
           python-version: '3.12'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
          
      - name: execute py script # run main.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
